### ISSUE TITLE
Things in the head of an Class declaration are singletons

### ISSUE THREAD

**Issue by Spindel** [jftuga/dcmp#2]
https://github.com/jftuga/dcmp/blob/0cdd771614a57160a523aedec57f5177d394f74e/dcmp.py#L49

You want to declare all the class variables inside the `__init__(self):` function  See below for why:

```
In [2]: class Foo:
   ...:     bar = []
   ...:     

In [3]: f = Foo()

In [4]: c = Foo()

In [5]: f.bar.append(1)

In [6]: c.bar
Out[6]: [1]
```

**Comment by jftuga** [comment]
When trying to this, I just added in a patch for `self.dir_queue` first before moving the other variables into `__init__(self)__`.

https://github.com/jftuga/dcmp/commit/3f4359ba774ca4531f272fb2c2e6178c8d63d933

Under Windows 10 and Python 3.6.3, I am now seeing this error which was not occurring before.  I am not sure on how to fix this.

    Traceback (most recent call last):
      File "c:\Python36\lib\multiprocessing\queues.py", line 234, in _feed
        obj = _ForkingPickler.dumps(obj)
      File "c:\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
        cls(buf, protocol).dump(obj)
    TypeError: can't pickle _thread.lock objects
    Traceback (most recent call last):
      File "c:\Python36\lib\multiprocessing\queues.py", line 234, in _feed
        obj = _ForkingPickler.dumps(obj)
      File "c:\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
        cls(buf, protocol).dump(obj)
    TypeError: can't pickle _thread.lock objects
    Traceback (most recent call last):
      File "c:\Python36\lib\multiprocessing\queues.py", line 234, in _feed
        obj = _ForkingPickler.dumps(obj)
      File "c:\Python36\lib\multiprocessing\reduction.py", line 51, in dumps
        cls(buf, protocol).dump(obj)
    TypeError: can't pickle _thread.lock objects

How can this be fixed so that Exceptions do not occur and this variable is defined inside of init()? Also commenting out line 49 `dir_queue = None` did not help either.

**Comment by Spindel** [comment]
The problem you're seeing is that you're calling `Pickle` (to serialize) Things that cannot be serialized.

Pickle can store data, but if an object contains  threads ( which is per-process Mutable state, ie. things that change, and are different every time you run it)  you cannot then pickle them.

This is a typical sign that you are blending "runtime" logic with "data" logic, and the two get confused, when you try to save it.
